version: "3.6"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    ports:
      - 5433:5432
    networks:
      - services

  app:
    image: igags/askcard:latest
    depends_on:
      - db
      - cache
    networks:
      - services
    env_file:
      - "./.env"
    ports:
      - 9094:80
    expose:
      - 9094
    restart: always
  
  cache:
    image: redis:latest
    networks:
      - services
    ports:
      - 6381:6379
    expose:
      - 6381
networks:
  services: