version: "3.6"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - services
  app:
    image: askcard:latest
    depends_on:
      - db
    networks:
      - services
    env_file:
      - "./.env"
    ports:
      - 9094:80
    expose:
      - 9094
    restart: always
networks:
  services: