version: '3.6'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1234

  ask-card-api:
    image: igags/askcard
    restart: always
    ports:
      - 5000:80
    env_file: 
      - ".env"
